server:
  port: 8001
  servlet:
    context-path: /
spring:
  application:
    name: CoreEngine
  data:
    elasticsearch:
      repositories:
        enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: waves
    template:
      default-topic: raw
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    lease-expiration-duration-in-seconds: 240
    lease-renewal-interval-in-seconds: 120
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    eviction-interval-timer-in-ms: 50000
    enable-self-preservation: true
    renewal-threshold-update-interval-ms: 120000
    use-read-only-response-cache: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  # static properties
  app:
    name: ${spring.application.name}
    description: --

logging:
  level:
    root: error
    org:
      apache:
        kafka: info
    com:
      globant:
        brainwaves: info
      netflix:
        discovery: off
        eureka: off
